version: '3.8'
services:
  eureka1-srv:
    image: sc/eureka:latest
    environment:
      - SPRING.PROFILES.ACTIVE=eureka1
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://eureka2-srv:18762/eureka/
    ports:
      - '18761:18761'
    networks:
      - scnet
  eureka2-srv:
    image: sc/eureka:latest
    environment:
      - SPRING.PROFILES.ACTIVE=eureka2
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://eureka1-srv:18761/eureka/
    ports:
      - '18762:18762'
    networks:
      - scnet
  product-db:
    image: mongo:5.0.3
    ports:
      - '27017:27017'
    volumes:
      - "/home/peda/Atit/Practice/spring-microservice/data/mongo:/data/db"
    networks:
      - scnet
  cart-db:
    image: mysql:5.7.31
    environment:
      - MYSQL_ROOT_PASSWORD=root10
      - MYSQL_DATABASE=cartdb
      - MYSQL_USER=cartdbuser
      - MYSQL_PASSWORD=cartdbuser10
    volumes:
      - "/home/peda/Atit/Practice/spring-microservice/data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - scnet
  product-srv:
    image: sc/product:latest
    environment:
      - SPRING.PROFILES.ACTIVE=docker
      - MONGO.HOST=product-db
      - MONGO.PORT=27017
      - MONGO.DB=productdb
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://eureka1-srv:18761/eureka/,http://eureka2-srv:18762/eureka/
    networks:
      - scnet
    ports:
      - '5000-5001:5000'
    deploy:
      replicas: 2
    depends_on:
      - product-db
      - eureka1-srv
      - eureka2-srv
  cart-srv:
    image: sc/cart:latest
    ports:
      - "6000:6000"
    environment:
      - CARTDB.JDBCURL=jdbc:mysql://cart-db:3306/cartdb
      - CARTDB.USERNAME=cartdbuser
      - CARTDB.PASSWORD=cartdbuser10
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://eureka1-srv:18761/eureka/,http://eureka2-srv:18762/eureka/
    networks:
      - scnet
    depends_on:
      - cart-db
      - eureka1-srv
      - eureka2-srv
  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - '/home/peda/Atit/Practice/spring-microservice/data/prometheus:/etc/prometheus'
    networks:
      - scnet
    ports:
      - '9090:9090'
    depends_on:
      - product-srv
      - cart-srv
networks:
  scnet:
    driver: bridge
