scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "eureka-1"
    scrape_interval: 5s
    eureka_sd_configs:
      - server: http://eureka1-srv:18761/eureka
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__address__]
        target_label: instance
  - job_name: "eureka-2"
    scrape_interval: 5s
    eureka_sd_configs:
      - server: http://eureka2-srv:18762/eureka
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__address__]
        target_label: instance
